name       : cdemu-daemon
homepage   : https://sourceforge.net/projects/cdemu/
version    : 3.0.5
release    : 2
source     :
    - https://sourceforge.net/projects/cdemu/files/cdemu-daemon/cdemu-daemon-3.0.5.tar.bz2 : 317ca9149eb902c10a6ef9799976320b2f2d1bc42cb47ab68dbd151f5cf780b1
license    : GPL-2.0
component  : system.utils
summary    : CD Emulation Daemon 
description: |
    CD-EMU provides CD/DVD Drive emulation for Linux. This package contains
    the daemon portion.
builddeps  :
    - pkgconfig(ao)
    - pkgconfig(libmirage)
rundeps    :
    - vhba-module
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
