name       : cdemu-daemon
homepage   : https://sourceforge.net/projects/cdemu/
version    : 3.2.1
release    : 4
source     :
    - https://sourceforge.net/projects/cdemu/files/cdemu-daemon/cdemu-daemon-3.2.1.tar.bz2 : 842d889094be45fb913ee6649cba8f12e6190e83497764536bc63d1c3fc3389c
license    : GPL-2.0-or-later
component  : system.utils
summary    : CD Emulation Daemon
description: |
    CD-EMU provides CD/DVD Drive emulation for Linux. This package contains
    the daemon portion.
builddeps  :
    - pkgconfig(ao)
    - pkgconfig(libmirage)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
