name       : cdemu-daemon
homepage   : https://sourceforge.net/projects/cdemu/
version    : 3.2.2
release    : 5
source     :
    - https://datapacket.dl.sourceforge.net/project/cdemu/cdemu-daemon/cdemu-daemon-3.2.2.tar.bz2 : 2b8934ad09d5a1c844202d5e2020193dd5bb00112732559c23594b0761f63542
license    : GPL-2.0-or-later
component  : system.utils
summary    : CD Emulation Daemon
description: |
    CD-EMU provides CD/DVD Drive emulation for Linux. This package contains
    the daemon portion.
builddeps  :
    - pkgconfig(ao)
    - pkgconfig(libmirage)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
