name       : cdemu-daemon
homepage   : https://sourceforge.net/projects/cdemu/
version    : 3.2.3
release    : 6
source     :
    - https://sourceforge.net/projects/cdemu/files/cdemu-daemon/cdemu-daemon-3.2.3.tar.bz2/download : b94bd9f343b82a292ea542c6454762ae4d5987a78387d36a5a5c335bf9fb5d08
license    : GPL-2.0-or-later
component  : system.utils
summary    : CD Emulation Daemon
description: |
    CD-EMU provides CD/DVD Drive emulation for Linux. This package contains
    the daemon portion.
builddeps  :
    - pkgconfig(ao)
    - pkgconfig(libmirage)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
