name       : cdemu-daemon
homepage   : https://sourceforge.net/projects/cdemu/
version    : 3.2.4
release    : 8
source     :
    - https://sourceforge.net/projects/cdemu/files/cdemu-daemon/cdemu-daemon-3.2.4.tar.bz2/download : a6b32d4b78631e5f449f05f8d26b7f2f46dd3e82387f5855ccabb4933592de0b
license    : GPL-2.0-or-later
component  : system.utils
summary    : CD Emulation Daemon
description: |
    CD-EMU provides CD/DVD Drive emulation for Linux. This package contains
    the daemon portion.
builddeps  :
    - pkgconfig(ao)
    - pkgconfig(libmirage)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
