name       : cdemu-daemon
homepage   : https://sourceforge.net/projects/cdemu/
version    : 3.2.6
release    : 9
source     :
    - https://sourceforge.net/projects/cdemu/files/cdemu-daemon/cdemu-daemon-3.2.6.tar.xz/download : a6e404e3ef75c6146e36354f65880dfd63b4b8ef1f54039dc5058e190f857d8f
license    : GPL-2.0-or-later
component  : system.utils
summary    : CD Emulation Daemon
description: |
    CD-EMU provides CD/DVD Drive emulation for Linux. This package contains
    the daemon portion.
builddeps  :
    - pkgconfig(ao)
    - pkgconfig(libmirage)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 service-example/cdemu-daemon.service $installdir/usr/lib/systemd/user/cdemu-daemon.service
    install -Dm00644 service-example/net.sf.cdemu.CDEmuDaemon.service $installdir/usr/share/dbus-1/services/net.sf.cdemu.CDEmuDaemon.service